name: Deploy image to private registry
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY_API_TOKEN: ${{ secrets.REGISTRY_API_TOKEN }}
      REGISTRY_API_URL: ${{ vars.REGISTRY_API_URL }}
      REGISTRY_NAME: ${{ vars.REGISTRY_NAME }}    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the docker image
        shell: bash
        run: |
          docker build . -t ${REGISTRY_API_URL}/${REGISTRY_NAME}/openai/langchain-frontend:0.0.1
      - name: Publish the docker image
        shell: bash
        run: |
          echo ${REGISTRY_API_TOKEN} | xargs -I {} docker login ${REGISTRY_API_URL} -u {} -p {}
          docker image push ${REGISTRY_API_URL}/${REGISTRY_NAME}/openai/langchain-frontend:0.0.1
          docker logout ${REGISTRY_API_URL}
